### ISSUE TITLE
Close button in the Modal header not working even in the demos

### ISSUE THREAD

**Issue by ghost** [algm/reactstrap-confirm#1]
I like your repo but I only have an issue regarding the close button can you please fix this?

**Comment by ghost** [comment]
I have found a solution just add this line in Modal.js file
`_this.toggle = _this.toggle.bind(_this);`
after these lines in the constructor
```
 _this.confirm = _this.confirm.bind(_this);
 _this.cancel = _this.cancel.bind(_this);
+...
```

**Comment by algm** [comment]
Thank you for noticing, I will fix it this weekend :)
