### ISSUE TITLE
How can I have the confirm button at left of cancel button?

### ISSUE THREAD

**Issue by rapomon** [algm/reactstrap-confirm#12]
I suggest a new flag confirmFirst (false by default) for showing the confirm button before the cancel button.

There is any way to do this without touching code?

For example, in Windows we have the most important button 'Accept', 'Confirm' etc, always the first, and all buttons aligned at right, of course.

**Comment by algm** [comment]
I can add an option which receives the ok and cancel events and state as parameters so you can override that part of the component. Would that be ok?

**Comment by rapomon** [comment]
Ok, that's right! Thank you!
