### ISSUE TITLE
Missing default className reactstrap-confirm in div modal-dialog

### ISSUE THREAD

**Issue by rapomon** [algm/reactstrap-confirm#16]
The default className `reactstrap-confirm` of `<div class="modal-dialog">` does not exist anymore?

**Comment by algm** [comment]
Yes it does:

https://github.com/algm/reactstrap-confirm/blob/master/src/components/ConfirmModal.js#L40

**Comment by rapomon** [comment]
Ok, I looked up the code before writing the issue, but the class not appear.

**Comment by algm** [comment]
I can't reproduce the issue, could you provide a test case?

**Comment by rapomon** [comment]
Sorry, now the class exists, maybe it was the cache or something like that.
