### ISSUE TITLE
Clashes with default `confirm()` function

### ISSUE THREAD

**Issue by C0DK** [algm/reactstrap-confirm#17]
![image](https://user-images.githubusercontent.com/9048078/67763673-8788f580-fa48-11e9-94bd-d7ff99d78bf0.png)

It doesn't fail for me on your demo site, but when simply using it as `confirm()` it shows the above. Is there a way to set the default values? :) Do i have to manually set the defaults?

**Comment by C0DK** [comment]
Nevermind - your functionname just clashes with this https://www.w3schools.com/jsref/met_win_confirm.asp - so my editor wasn't asking if i wanted to import your version. Maybe the name should be unique (atleast from default functions)

**Comment by algm** [comment]
You can just import it as something else, like:

```js
import myConfirm from 'reactstrap-confirm'
```

**Comment by C0DK** [comment]
My main problem was that i hadn't imported it, but didn't get any warning that it wasn't imported, as i had A function called `confirm`
