### ISSUE TITLE
Update reactstrap dependency version

### ISSUE THREAD

**Issue by zedtux** [algm/reactstrap-confirm#2]
```
warning " > reactstrap-confirm@1.0.4" has incorrect peer dependency "reactstrap@^6.2.0".
```

The latest version of reactstrap seems to be 8 today, can you please update the version?

**Comment by algm** [comment]
It should be fixed in the new version, please confirm it if you can

**Comment by zedtux** [comment]
Thank you @algm for your update, unfortunately when I ran `yarn upgrade-interactive` and selected to update `reactstrap-confirm`, I had the following:

```
warning " > reactstrap-confirm@1.1.0" has incorrect peer dependency "reactstrap@>=^6.2.0".
```
