### ISSUE TITLE
[Feature request] Let users pass extra props to Modal component

### ISSUE THREAD

**Issue by eshaan7** [algm/reactstrap-confirm#25]
https://github.com/algm/reactstrap-confirm/blob/82544fe785e213f06eacf678360f7b465937bbe7/src/components/ConfirmModal.js#L15

In the most basic sense, what I mean is:

Use `const {onClose, ...modalProps} = props` for de-structuring and then `<Modal {...modalProps}>....</Modal>`.

This would allow users the ability to pass extra props like `backdrop`, `keyboard`, etc which are supported by reactstrap's `Modal` component.

**Comment by algm** [comment]
Implemented, will be added in version 1.3
