### ISSUE TITLE
Allow passing a disabled option or a component prop to the confirm button

### ISSUE THREAD

**Issue by zedtux** [algm/reactstrap-confirm#3]
I need to be able to enable/disable the confirmation button (use case: disable the confirm button while loading something, when done, enable the confirm button), so I would need either a boolean `confirmDisabled` option, either a `confirmButton` prop to which I can pass a `<Button />` component.

**Comment by algm** [comment]
Could you add a code example of how you think this should work?

**Comment by zedtux** [comment]
Since I've opened this issue, I changed the way I'm using `reactstrap-confirm` so that I have no code example to share with you.

## But

But as far as I remember, I've made a component which uses `reactstrap-confirm`, and this component was asking confirmation to do an action, but in order to build that sentence, an API call was made and its result was returning the needed data (all this stuff using redux of course).

I wanted to disable the "Confirm" button while it was doing the server request, and when the data was retrieved, and the sentence displayed, then the "Confirm" button could be enabled.

## Another use case

Another use case I could think of is a modal with a licence to be accepted. The user scrolls to the end of the licence and when he reaches the bottom of the text, then the "Accept" button would be enabled, while it was disabled until that.

## So now?

Right now, I don't have the time to build a code example, sorry, so :

 - either you keep the issue open, remind me later (like in 2 months)
 - either you close that issue, and if I remember and have time, I'll prepare that code example, or if someone pass by and can provide this code example ...

**Comment by algm** [comment]
Ok, here is the proposed solution:

I can make an option which is a promise, whenever that promise is resolved with "true", the button gets enabled. That way you can bind the button behavior to anything you need.

**Comment by zedtux** [comment]
Thank you for the proposal, I think that should work in the way you made this component.
