### ISSUE TITLE
ERROR reactstrap-confirm: Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by codingyourlife** [algm/reactstrap-confirm#6]
When trying to installing another npm package afterwards I receive this error:

> npm ERR! path /[MyProjPath]/node_modules/reactstrap-confirm
> npm ERR! code EISGIT
> npm ERR! git /[MyProjPath]/node_modules/reactstrap-confirm: Appears to be a git repo or submodule.
> npm ERR! git     /[MyProjPath]/node_modules/reactstrap-confirm
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.

I tried removing the node_modules folder, npm install then installing the other package and it failed again

I then tried removing this reactstrap-confirm package, installing the other package and this works

I think the .git folder somehow became part of the npm package?

Version: 1.1.0

So again to make it totally clear: Installing of reactstrap-confirm makes NO problem but installing a different package afterwards seems to fail (in my case react-widgets)

**Comment by laxman1129** [comment]
I am also getting same issue... If we delete .git folder from `node_modules\reactstrap-confirm` folder then it builds successfully.

If package is published without .git folder then this workaround is not needed.

**Comment by constantinpojoga** [comment]
Same here, `rm -rf node_modules/*/.git/` removed the error

**Comment by constantinpojoga** [comment]
Removed the error and refactored few components: https://github.com/algm/reactstrap-confirm/pull/7

**Comment by algm** [comment]
> Removed the error and refactored few components: #7

Thank you for that! merging.
