### ISSUE TITLE
Allow passing the size parameter

### ISSUE THREAD

**Issue by zedtux** [algm/reactstrap-confirm#8]
The reactstrap modal has the `size` property which defines the modal's size and AFAIK the reactstrap-confirm component do not allow changing it.

```js
Modal.propTypes = {
  // ...
  // corresponds to bootstrap's modal sizes, ie. 'lg' or 'sm'
  size: PropTypes.string,
  // ...
}
```

**Comment by algm** [comment]
Good one, will add it in the next release
